-- Run this in your Supabase SQL Editor to create the necessary table
-- https://app.supabase.com/project/_/sql

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY,
    username TEXT NOT NULL,
    phone_number TEXT UNIQUE,
    deleted BOOLEAN DEFAULT false,
    coins INTEGER DEFAULT 0,
    level INTEGER DEFAULT 1,
    best_wpm NUMERIC DEFAULT 0,
    avg_wpm NUMERIC DEFAULT 0,
    avg_accuracy NUMERIC DEFAULT 0,
    races_played INTEGER DEFAULT 0,
    wins INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.race_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    wpm NUMERIC NOT NULL,
    accuracy NUMERIC NOT NULL,
    mode TEXT NOT NULL, -- 'practice', 'bot', 'multiplayer'
    won BOOLEAN DEFAULT false,
    coins_earned INTEGER DEFAULT 0,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (optional but recommended)
-- ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows the service role key to do everything
-- (The app uses the service role key server-side)
-- CREATE POLICY "Service role full access" ON public.users 
-- FOR ALL USING (auth.role() = 'service_role');

-- MIGRATION STATEMENTS FOR EXISTING DATABASES
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS phone_number TEXT UNIQUE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT false;
